// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lapr5_masterdata_viagens.Infrastructure;

namespace lapr5_masterdata_viagens.Migrations
{
    [DbContext(typeof(ViagensDbContext))]
    partial class ViagensDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("lapr5_masterdata_viagens.Domain.DriverDuties.DriverDuty", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("DriverDuties");
                });

            modelBuilder.Entity("lapr5_masterdata_viagens.Domain.Drivers.Driver", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DriverLicenseExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverLicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypesIDs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DriverLicenseNumber")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("lapr5_masterdata_viagens.Domain.Trips.PassingTime", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NodeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeInstant")
                        .HasColumnType("int");

                    b.Property<string>("TripId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("PassingTimes");
                });

            modelBuilder.Entity("lapr5_masterdata_viagens.Domain.Trips.Trip", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LineID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Orientation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleDutyId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("VehicleDutyId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("lapr5_masterdata_viagens.Domain.VehicleDuties.VehicleDuty", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("VehicleDuties");
                });

            modelBuilder.Entity("lapr5_masterdata_viagens.Domain.Vehicles.Vehicle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CarPlateCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ServiceStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleTypeID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarPlateCode")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("lapr5_masterdata_viagens.Domain.Workblocks.Workblock", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DriverDutyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EndTime")
                        .HasColumnType("int");

                    b.Property<int>("StartTime")
                        .HasColumnType("int");

                    b.Property<string>("TripsIDs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleDutyId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DriverDutyId");

                    b.HasIndex("VehicleDutyId");

                    b.ToTable("Workblocks");
                });

            modelBuilder.Entity("lapr5_masterdata_viagens.Domain.Trips.PassingTime", b =>
                {
                    b.HasOne("lapr5_masterdata_viagens.Domain.Trips.Trip", null)
                        .WithMany("PassingTimes")
                        .HasForeignKey("TripId");
                });

            modelBuilder.Entity("lapr5_masterdata_viagens.Domain.Trips.Trip", b =>
                {
                    b.HasOne("lapr5_masterdata_viagens.Domain.VehicleDuties.VehicleDuty", null)
                        .WithMany("Trips")
                        .HasForeignKey("VehicleDutyId");
                });

            modelBuilder.Entity("lapr5_masterdata_viagens.Domain.Workblocks.Workblock", b =>
                {
                    b.HasOne("lapr5_masterdata_viagens.Domain.DriverDuties.DriverDuty", null)
                        .WithMany("Workblocks")
                        .HasForeignKey("DriverDutyId");

                    b.HasOne("lapr5_masterdata_viagens.Domain.VehicleDuties.VehicleDuty", null)
                        .WithMany("Workblocks")
                        .HasForeignKey("VehicleDutyId");
                });

            modelBuilder.Entity("lapr5_masterdata_viagens.Domain.DriverDuties.DriverDuty", b =>
                {
                    b.Navigation("Workblocks");
                });

            modelBuilder.Entity("lapr5_masterdata_viagens.Domain.Trips.Trip", b =>
                {
                    b.Navigation("PassingTimes");
                });

            modelBuilder.Entity("lapr5_masterdata_viagens.Domain.VehicleDuties.VehicleDuty", b =>
                {
                    b.Navigation("Trips");

                    b.Navigation("Workblocks");
                });
#pragma warning restore 612, 618
        }
    }
}
